language: node_js
node_js:
- node
sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn --version
- yarn install
- yarn setup
- yarn lint
- yarn test:nsp-warn
- yarn test:coverage
after_success:
- yarn test:codacy-upload
- yarn test:codecov-upload
after_script:
- cat ./bin/test/nohup.out
before_deploy:
- cd dist
deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  skip_cleanup: true
  api_key:
    secure: uSVuc9wGUY/saaOnh4cak7ASl5us5dv32DCmemSmCWwp+PxHJprKsF/Xfvo6KGQbpjwIeg6UUpPHyFglHPICXQIu1DXApZ3y3by6uu6bfxvVipNFv9LfQjmhlJu8VEs0Kx8r3a/XRmQUqeVlg5Qi1EpytFvUExz0I6tLpkvjyl0ljIdz6M/LXS2Y/HIrUCAPKgxuzzEJphgGJwaYYLwvJS25HzmCPaV1VYdYh17+MOEEQf9qZsboHR+ceO0Xsi0fY8IkJfjLkyZOteHf35Cu5JErIilDY6ccKnmU4bTnVzaCh7jCqE9aNP++JT5vCqc5Tn17lb6psYj+iqK07574g0pHTcd8RR85sy76Jemh22TTl5lx6B4MNUR9JENReawudQUF2emdgGHkX8bBp08Pq6j5IYL3Tlc70jBDLxE19Ya7aEt4KkXrLNffVX9GRA5mkexdA1od342RSaL9mmxi/PwIGkcxcKwag47pSx8MXXE9c6uDJWONKhBHJ2JE73gccjr9h/FZiZj1arsdooSygD45E2R3itVQXOET0dF+IcvIraU4ZVFCPTRI2sB5gQPEcemPi7HdGxJ/kouGJooqMNkCDA/ZOnesPsJn+XuLczuamt3ZTMV1pOaqRf56Pxzon8Fh1UKf0cI3jbR77Cr1XQK2LDbYiJtAW4X6xCQCNws=
  on:
    tags: true
    repo: hmcts/em-viewer-web
