version: '2.1'

services:

  em-annotation-app:
    image: docker.artifactory.reform.hmcts.net/evidence/em-annotation-app:latest
    environment:
      - NODE_ENV=development
      - SERVER_PORT=8080
      - IDAM_USER_BASE_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://em-annotation-database:5432/annotation
      - SPRING_DATASOURCE_USERNAME=annotation
      - SPRING_DATASOURCE_PASSWORD=annotation
      - http_proxy=
      - https_proxy=
      - no_proxy=
#      logging env vars
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=true
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=em-annotation-app
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=em-annotation-app
      - PACKAGES_VERSION=unkown
#      debug mode
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    links:
     - em-annotation-database
     - document-management-store
     - idam-api
     - service-auth-provider-api
    depends_on:
     - em-annotation-database
     - document-management-store
     - idam-api
     - service-auth-provider-api

  em-annotation-database:
    image: docker.artifactory.reform.hmcts.net/evidence/em-annotation-app-database:latest
